### PR TITLE
Rustem kavaklik finished his branch

### PR DESCRIPTION
**Pull request by rustemkvk**
Check it please

### CODE REVIEW

**Comment by uccaybioralet** [comment]
Perfect!

**Comment by uccaybioralet** [comment]
Excellent!

**Comment by AtilaKilicarslan** [comment]
Fantastic !

**Comment by Ali-1977000** [comment]
Good work

**Comment by hamzasahbaz** [comment]
Great!

**Comment by RasimKilicarslan** [comment]
Great

**Review by AdemYildiz1 — COMMENTED** [review]
cool

**Review by uccaybioralet — APPROVED** [review]
I approve

**Review by mehmetumuttekagac — APPROVED** [review]
Great

**Pull request merged**
